name: TryMC-CagePlugin
version: 1.0-beta
author: vFasteeQ
website: completionStudio.pl
main: pl.vfasteeq.cageplugin.MCPlugin

commands:
  acage:
    description: Admin options for a cage plugin...
  cage:
    description: Start a cage with two players...